apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: azurite
  name: azurite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurite
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: azurite
    spec:
      containers:
        - image: mcr.microsoft.com/azure-storage/azurite
          name: azurite
          command: ["azurite-blob"]
          args: ["-l", "/data", "--blobHost", "0.0.0.0"]
          env:
            - name: AZURITE_ACCOUNTS
              valueFrom:
                secretKeyRef:
                  name: azurite
                  key: AZURITE_ACCOUNTS
          ports:
            - containerPort: 10000
          volumeMounts:
            - mountPath: /data
              name: data-volume
      volumes:
      - name: data-volume
        hostPath:
          path: /run/desktop/mnt/host/d/tmp/azurite/data
          type: DirectoryOrCreate
