apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurecosmosdb
  labels:
    app: azurecosmosdb
spec:
  storageClassName: hostpath
  capacity:
    storage: 30Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: /run/desktop/mnt/host/d/tmp/azure-cosmos-db/data
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurecosmosdb
  labels:
    app: azurecosmosdb
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 30Gi