apiVersion: v1
kind: Service
metadata:
  name: azurite
  labels:
    app: azurite
spec:
  type: LoadBalancer
  ports:
    - port: 10000
      protocol: TCP
      targetPort: 10000
  selector:
    app: azurite
status:
  loadBalancer: {}