kubectl apply -f azurecosmosdb-secret.yaml
kubectl apply -f azurecosmosdb-service.yaml
kubectl apply -f azurecosmosdb-deployment.yaml
kubectl apply -f azurite-secret.yaml
kubectl apply -f azurite-service.yaml
kubectl apply -f azurite-deployment.yaml
#kubectl port-forward deployment/azurecosmosdb 8081:8081
#kubectl port-forward deployment/azurecosmosdb 10251:10251
#kubectl port-forward deployment/azurecosmosdb 10252:10252
#kubectl port-forward deployment/azurecosmosdb 10253:10253
#kubectl port-forward deployment/azurecosmosdb 10254:10254
#kubectl port-forward deployment/azurite 10000:10000