version: '3'

services:

  cosmos:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    mem_limit: 3g
    cpu_count: 2
    environment:
        AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 20
        AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: "true"
    volumes:
        - /var/run/docker.sock:/var/run/docker-host.sock

  app:
    depends_on:
      - "cosmos"
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] Update 'VARIANT' to pick a .NET Core version: 2.1, 3.1, 5.0
        VARIANT: 5.0
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock 
      - ..:/workspace:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:cosmos

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)    