name: Build and run paula-dev-migrator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release ./src/data/Migrator/Migrator.csproj

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/Migrator ./src/data/Migrator/Migrator.csproj
       
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .migrator-app
          path: ${{env.DOTNET_ROOT}}/Migrator

  run:
    runs-on: ubuntu-latest
    needs: build
    env:
      CosmosEndpoint: ${{secrets.AZURE_COSMOS_DB_PAULA_DEV_ENDPOINT}}
      CosmosKey: ${{secrets.AZURE_COSMOS_DB_PAULA_DEV_KEY}}
      CosmosDatabase: 'Paula'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .migrator-app

      - name: Run migrator
        run: dotnet Migrator.dll
